[workspace]
members = ["zexcavator-cli", "zexcavator-lib", "zexcavator-tui"]

[workspace.dependencies.zingolib]
git = "https://github.com/zingolabs/zingolib.git"
branch = "dev"
features = ["test-elevation"]
package = "zingolib"
