name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --all --verbose
    - name: Test
      run: cargo test --all --verbose

    # - name: Clippy
    #   run: cargo clippy --all -- -D warnings

    - name: Format Check
      run: cargo fmt --all -- --check
